analytics: {}
color:
  brandColors:
    - '#90A0B0'
    - '#182838'
    - '#8090A8'
    - '#4D80B3'
    - '#000000'
  brandStrength: 0.16791
  lightness: 0.007728
  rhythmicContrast: 0.586101
  saturation: 0.957141
cta: {}
layout_spectrum: 0.002798
name: John Forrest
opengraph: {}
purpose: {}
typography_spectrum: 0.195895
