analytics: {}
color:
  brandColors:
    - '#C8D8E0'
    - '#295C4C'
    - '#60A888'
    - '#409078'
    - '#C07898'
  brandStrength: 0.16791
  lightness: 0.007728
  rhythmicContrast: 0.586101
  saturation: 0.957141
cta: {}
layout_spectrum: 0.002798
name: John Forrest
opengraph: {}
purpose: {}
typography_spectrum: 0.195895
