name: John Forrest
favicon: null
layout_spectrum: 0.585585
typography_spectrum: 0.195895
title: John Forrest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B0B0'
    - '#6D2118'
    - '#908080'
    - '#B83828'
    - '#F0D8B0'
  brandStrength: 0.16791
  lightness: 0.007728
  saturation: 0.957141
  rhythmicContrast: 0.586101
purpose:
  - name: null
    item: null
    url: null
