analytics: {}
color:
  brandColors:
    - '#B8B0B0'
    - '#6D2118'
    - '#908080'
    - '#B83828'
    - '#F0D8B0'
  brandStrength: 0.16791
  lightness: 0.007728
  rhythmicContrast: 0.586101
  saturation: 0.957141
cta: {}
layout_spectrum: 0.585585
name: John Forrest
opengraph: {}
purpose: {}
typography_spectrum: 0.195895
